### ISSUE TITLE
missing the process_NCM_dataset.ipynb notebook

### ISSUE THREAD

**Issue by hilinxinhui** [Ruifeng-Tan/MAGNet#1]
Thank you for your excellent work. While studying your code, I noticed that the file `process_NCM_dataset.ipynb`, which is used for handling the NCM dataset, seems to be missing from this repository. Could you kindly take some time to check on this? I would greatly appreciate it.

**Comment by Ruifeng-Tan** [comment]
Thank you for your comments. The `process_NCM_dataset.ipynb`  is now available at https://drive.google.com/drive/folders/1iHu32xrkbNOzqbQM9qH-RXMdxxzj3TZm

**Comment by hilinxinhui** [comment]
Thank you for your prompt reply!
